name: build
on: push
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: Gemfile
      USE_OFFICIAL_GEM_SOURCE: 1
    steps:
      - uses: actions/checkout@v2
      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: "3.1"
          bundler-cache: true
          cargo-cache: true
          cargo-vendor: true
      - run: bundle exec rake compile && bundle exec rake test
